import React from 'react';
import type { BlockFieldDef, BlockTypeDef } from '../model';
import {
    MdDescription, MdGpsFixed, MdTextSnippet, MdSwapHoriz,
    MdHelp, MdLink,
    MdVisibility, MdDashboard, MdScience,
    MdBuild, MdBiotech, MdChecklist, MdMyLocation,
    MdMedication, MdPets, MdGroup,
    MdInventory, MdAutoStories, MdPeople, MdStorage,
    MdQueryStats, MdAutoGraph, MdLeaderboard, MdSpeed,
    MdRule, MdBarChart, MdFunctions, MdAccountTree,
    MdSearch, MdAssessment, MdCalculate, MdFactCheck,
    MdWarning, MdLightbulb, MdFlashOn, MdCheckCircleOutline,
    MdHelpOutline, MdAutoAwesome, MdUpdate, MdLightbulbOutline,
    MdFormatQuote, MdHourglassBottom, MdImage, MdCode,
    MdAttachMoney, MdBalance, MdTrendingUp, MdPlayArrow, MdFormatListNumbered, MdTimeline,
} from 'react-icons/md';

const icon = (Component: React.ComponentType<{ size?: number; className?: string }>) =>
    React.createElement(Component, { size: 14 });

// Поле «Последовательность»: uuid-list-ссылки на атомарные блоки-триплеты
// (statement «Прямой триплет», entity «Сущность», action «Действие») в порядке следования.
const TRIPLET_SEQUENCE_FIELD: BlockFieldDef = {
    key: 'sequence',
    label: 'Последовательность (триплеты)',
    inputType: 'uuid-list',
    placeholder: 'атомарный триплет',
    addLabel: 'Добавить триплет',
    uuidRefBlockTypes: ['statement', 'entity', 'action'],
    helpText: 'Ссылки на блоки-триплеты (statement «Прямой триплет», entity «Сущность», action «Действие») в порядке следования. Каждый шаг — отдельный блок-триплет.',
};

export const BLOCK_TYPES: BlockTypeDef[] = [
    {
        designation: 'metadata',
        name: 'Метаданные',
        icon: icon(MdDescription),
        color: '#6366f1',
        canAddMultiple: false,
        layout: 'yaml',
        description: 'DOI, название, авторы статьи',
        fields: [
            { key: 'doi', label: 'DOI', inputType: 'text', placeholder: '10.xxxx/xxxxx' },
            { key: 'title', label: 'Название статьи', inputType: 'textarea', placeholder: 'Title of the article' },
            { key: 'authors', label: 'Авторы', inputType: 'text-list', placeholder: 'Фамилия И.' },
        ],
    },
    {
        designation: 'goal',
        name: 'Цель исследования',
        icon: icon(MdGpsFixed),
        color: '#8b5cf6',
        canAddMultiple: true,
        layout: 'row',
        description: 'Триплет: субъект → предикат → объект. Используйте автодополнение для ссылок на другие блоки.',
        fields: [
            { key: 'subject', label: 'Субъект', inputType: 'uuid-ref', placeholder: 'исследование' },
            { key: 'predicate', label: 'Предикат', inputType: 'text', placeholder: 'цель' },
            { key: 'object', label: 'Объект', inputType: 'uuid-ref', placeholder: 'идентификация механизмов...' },
        ],
    },
    {
        designation: 'text',
        name: 'Свободный текст',
        icon: icon(MdTextSnippet),
        color: '#6b7280',
        canAddMultiple: true,
        description: 'Сплошной текст, для чего нет полей',
        fields: [
            { key: 'content', label: 'Текст', inputType: 'textarea', placeholder: 'Произвольный текст...' },
        ],
    },
    {
        designation: 'statement',
        name: 'Прямой триплет',
        icon: icon(MdSwapHoriz),
        color: '#059669',
        canAddMultiple: true,
        description: 'Универсальное поле для создания триплета',
        fields: [
            { key: 'subject', label: 'Субъект', inputType: 'text', placeholder: 'Субъект', required: true },
            { key: 'predicate', label: 'Предикат', inputType: 'text', placeholder: 'Предикат', required: true },
            { key: 'object', label: 'Объект', inputType: 'text', placeholder: 'Объект', required: true },
        ],
    },
    {
        designation: 'hypothesis',
        name: 'Гипотеза',
        icon: icon(MdHelp),
        color: '#dc2626',
        canAddMultiple: true,
        description: 'Что пытаемся опровергнуть',
        fields: [
            { key: 'hypothesis', label: 'Гипотеза', inputType: 'textarea', placeholder: 'Что пытаемся опровергнуть?' },
            { key: 'disproofExplanation', label: 'Почему нужно опровержение', inputType: 'textarea', placeholder: 'Пояснение почему нужно именно опровержение' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'prerequisite',
        name: 'Предпосылки',
        icon: icon(MdLink),
        color: '#7c3aed',
        canAddMultiple: false,
        description: 'Граф с онтологией, из которой исходит исследователь',
        fields: [
            { key: 'prerequisites', label: 'Предпосылки (утверждения)', inputType: 'textarea', placeholder: 'Каждое утверждение с новой строки' },
        ],
    },
    {
        designation: 'expectations',
        name: 'Ожидания',
        icon: icon(MdVisibility),
        color: '#2563eb',
        canAddMultiple: false,
        description: 'Что ожидаем получить после исследования',
        fields: [
            { key: 'expectations', label: 'Ожидания', inputType: 'textarea', placeholder: 'Что ожидаем получить?' },
        ],
    },
    {
        designation: 'research_design',
        name: 'Дизайн исследования',
        icon: icon(MdDashboard),
        color: '#0891b2',
        canAddMultiple: false,
        description: 'Тип исследования, рандомизация, ослепление, первичные/вторичные конечные точки',
        fields: [
            {
                key: 'studyType', label: 'Тип исследования', inputType: 'select',
                options: [
                    'Case Report',
                    'Case Series',
                    'Original Research',
                    'Review',
                    'Systematic Review',
                    'Meta-Analysis',
                    'Clinical Trial',
                    'Репликация',
                ],
            },
            { key: 'randomization', label: 'Рандомизация (RCT)', inputType: 'checkbox' },
            { key: 'blinding', label: 'Ослепление', inputType: 'checkbox' },
            { key: 'primaryEndpoints', label: 'Первичные конечные точки', inputType: 'text-list', placeholder: 'Каждая точка с новой строки' },
            { key: 'secondaryEndpoints', label: 'Вторичные конечные точки', inputType: 'text-list', placeholder: 'Каждая точка с новой строки' },
        ],
    },
    {
        designation: 'material',
        name: 'Материалы',
        icon: icon(MdScience),
        color: '#65a30d',
        canAddMultiple: false,
        description: 'Материалы, использованные в исследовании',
        fields: [
            { key: 'materials', label: 'Материалы', inputType: 'textarea', placeholder: 'Перечень материалов' },
        ],
    },
    {
        designation: 'method',
        name: 'Методы',
        icon: icon(MdBuild),
        color: '#475569',
        canAddMultiple: true,
        description: 'Методы и методы измерения',
        fields: [
            { key: 'methods', label: 'Методы', inputType: 'textarea', placeholder: 'Описание методов' },
            { key: 'measurementMethods', label: 'Методы измерения', inputType: 'textarea', placeholder: 'Как измерялись результаты' },
        ],
    },
    {
        designation: 'experiment',
        name: 'Эксперимент',
        icon: icon(MdBiotech),
        color: '#ea580c',
        canAddMultiple: true,
        description: 'Один эксперимент (повторяемый блок)',
        fields: [
            { key: 'experimentName', label: 'Название', inputType: 'text', placeholder: 'Сравнение A. russatus vs A. dimidiatus' },
            { key: 'experimentType', label: 'Тип', inputType: 'select', options: ['Поведенческий', 'Гистология', 'Western blot', 'RNA-seq', 'snRNA-seq', 'Интервенция in vivo', 'In vitro', 'Flow cytometry', 'Другое'] },
            { key: 'outcomes', label: 'Измеряемые показатели', inputType: 'tag-list', placeholder: 'rearing, grip strength, earhole closure, p16, SASP score, Il1b...' },
            { key: 'steps', label: 'Последовательность', inputType: 'uuid-list', placeholder: 'шаги по порядку', uuidRefBlockTypes: ['experiment_step'], helpText: 'Ссылки на блоки «Шаг эксперимента» в порядке выполнения' },
            { key: 'findings', label: 'Результаты (находки)', inputType: 'uuid-list', placeholder: 'результат', uuidRefBlockTypes: ['finding'], helpText: 'Ссылки на блоки «Результат (находка)»' },
            { key: 'duration', label: 'Длительность', inputType: 'text', placeholder: '2 недели, 5 недель, одномоментно...' },
            { key: 'experimentalPairs', label: 'Экспериментальные группы', inputType: 'pair-list', placeholder: 'группа + интервенция', pairGroupBlockTypes: ['animal_group'], pairInterventionBlockTypes: ['intervention'] },
            { key: 'controlPairs', label: 'Контрольные группы', inputType: 'pair-list', placeholder: 'группа + интервенция', pairGroupBlockTypes: ['animal_group'], pairInterventionBlockTypes: ['intervention'] },
        ],
    },
    {
        designation: 'inclusion_exclusion_criteria',
        name: 'Критерии включения/исключения',
        icon: icon(MdChecklist),
        color: '#16a34a',
        canAddMultiple: false,
        description: 'Критерии включения и исключения',
        fields: [
            { key: 'inclusionCriteria', label: 'Критерии включения', inputType: 'textarea', placeholder: 'Каждый критерий с новой строки' },
            { key: 'exclusionCriteria', label: 'Критерии исключения', inputType: 'textarea', placeholder: 'Каждый критерий с новой строки' },
        ],
    },
    {
        designation: 'biological_mechanism',
        name: 'Биологический механизм',
        icon: icon(MdBiotech),
        color: '#be185d',
        canAddMultiple: false,
        description: 'Описание биологического механизма',
        fields: [
            { key: 'mechanism', label: 'Механизм', inputType: 'textarea', placeholder: 'Описание биологического механизма' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'impact_goal',
        name: 'Объект воздействия',
        icon: icon(MdMyLocation),
        color: '#0d9488',
        canAddMultiple: true,
        description: 'На что воздействуем: клетка, ткань, орган, биологический путь',
        fields: [
            { key: 'cell', label: 'Клетка', inputType: 'text', placeholder: 'Тип клетки' },
            { key: 'tissue', label: 'Ткань', inputType: 'text', placeholder: 'Тип ткани' },
            { key: 'organ', label: 'Орган', inputType: 'text', placeholder: 'Орган' },
            { key: 'pathway', label: 'Биологический путь', inputType: 'text', placeholder: 'Название пути' },
            { key: 'substanceLevel', label: 'Уровень вещества', inputType: 'text', placeholder: 'Вещество и его уровень' },
        ],
    },
    {
        designation: 'intervention',
        name: 'Интервенция',
        icon: icon(MdMedication),
        color: '#e11d48',
        canAddMultiple: true,
        description: 'Дозировка, режим дозировки',
        fields: [
            { key: 'intervention', label: 'Интервенция', inputType: 'text', placeholder: 'Что делаем' },
            { key: 'dosage', label: 'Дозировка', inputType: 'text', placeholder: '10 мг/кг' },
            { key: 'dosageRegimen', label: 'Режим дозировки', inputType: 'text', placeholder: 'Ежедневно, 4 недели' },
        ],
    },
    {
        designation: 'animal_model',
        name: 'Животная модель',
        icon: icon(MdPets),
        color: '#a16207',
        canAddMultiple: true,
        description: 'Вид животного, временная шкала, условия',
        fields: [
            { key: 'species', label: 'Вид животного', inputType: 'text', placeholder: 'Mus musculus C57BL/6' },
            { key: 'timeline', label: 'Временная шкала', inputType: 'textarea', placeholder: 'События с указанием условий содержания' },
            { key: 'conditions', label: 'Условия', inputType: 'textarea', placeholder: 'Условия содержания и предыстория модели' },
        ],
    },
    {
        designation: 'entity',
        name: 'Сущность',
        icon: icon(MdInventory),
        color: '#1d4ed8',
        canAddMultiple: true,
        layout: 'row',
        description: 'Триплет: субъект → предикат → объект.',
        fields: [
            { key: 'subject', label: 'Субъект', inputType: 'uuid-ref', placeholder: 'выберите UUID' },
            { key: 'predicate', label: 'Предикат', inputType: 'text', placeholder: 'является сущностью' },
            { key: 'object', label: 'Объект', inputType: 'uuid-ref', placeholder: 'выберите UUID' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'definition',
        name: 'Определение понятия',
        icon: icon(MdAutoStories),
        color: '#4338ca',
        canAddMultiple: true,
        description: 'Определение термина',
        fields: [
            { key: 'term', label: 'Понятие', inputType: 'text', placeholder: 'Термин, который определяется' },
            { key: 'definition', label: 'Определение', inputType: 'textarea', placeholder: 'Определение понятия' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'assumptions',
        name: 'Предположения',
        icon: icon(MdVisibility),
        color: '#9333ea',
        canAddMultiple: false,
        description: 'Предположения, на которых основано исследование',
        fields: [
            { key: 'assumptions', label: 'Предположения', inputType: 'textarea', placeholder: 'Каждое предположение с новой строки' },
        ],
    },
    {
        designation: 'sample_size',
        name: 'Размер выборки',
        icon: icon(MdPeople),
        color: '#be123c',
        canAddMultiple: false,
        description: 'Размер выборки (n)',
        fields: [
            { key: 'sampleSize', label: 'n =', inputType: 'number', placeholder: '0' },
        ],
    },
    {
        designation: 'data_source',
        name: 'Источники данных',
        icon: icon(MdStorage),
        color: '#78716c',
        canAddMultiple: false,
        description: 'Откуда берутся данные',
        fields: [
            { key: 'dataSources', label: 'Источники', inputType: 'textarea', placeholder: 'Каждый источник с новой строки' },
        ],
    },
    {
        designation: 'probability_value',
        name: 'p-value',
        icon: icon(MdQueryStats),
        color: '#dc2626',
        canAddMultiple: true,
        description: 'Статистическая значимость',
        fields: [
            { key: 'pValue', label: 'p =', inputType: 'number', placeholder: '0.05' },
        ],
    },
    {
        designation: 'variance',
        name: 'Дисперсия',
        icon: icon(MdAutoGraph),
        color: '#b91c1c',
        canAddMultiple: false,
        description: 'Дисперсия данных',
        fields: [
            { key: 'variance', label: 'σ² =', inputType: 'number', placeholder: '0.0' },
        ],
    },
    {
        designation: 'effect_size',
        name: 'Размер эффекта',
        icon: icon(MdLeaderboard),
        color: '#c2410c',
        canAddMultiple: false,
        description: 'Размер эффекта (Cohen\'s d, odds ratio и т.д.)',
        fields: [
            { key: 'effectSize', label: 'Effect size =', inputType: 'number', placeholder: '0.0' },
            { key: 'effectType', label: 'Тип', inputType: 'select', options: ['Cohen\'s d', 'Odds Ratio', 'Hedge\'s g', 'eta²', 'Другое'] },
        ],
    },
    {
        designation: 'statistical_power',
        name: 'Мощность исследования',
        icon: icon(MdSpeed),
        color: '#9f1239',
        canAddMultiple: false,
        description: 'Статистическая мощность (1-β)',
        fields: [
            { key: 'power', label: 'Power (1-β) =', inputType: 'number', placeholder: '0.8' },
        ],
    },
    {
        designation: 'confidence_interval',
        name: 'Доверительный интервал',
        icon: icon(MdRule),
        color: '#881337',
        canAddMultiple: false,
        description: 'Confidence Interval (CI)',
        fields: [
            { key: 'ciLower', label: 'CI нижняя граница', inputType: 'number', placeholder: '0.0' },
            { key: 'ciUpper', label: 'CI верхняя граница', inputType: 'number', placeholder: '0.0' },
            { key: 'ciLevel', label: 'Уровень CI', inputType: 'select', options: ['90%', '95%', '99%'] },
        ],
    },
    {
        designation: 'magnitude_value',
        name: 'Числа с названиями',
        icon: icon(MdBarChart),
        color: '#1e40af',
        canAddMultiple: false,
        description: 'Числа вместе с их названием и величинами',
        fields: [
            { key: 'namedNumbers', label: 'Числа', inputType: 'key-value-list', placeholder: 'Каждая строка: название: значение' },
        ],
    },
    {
        designation: 'formula',
        name: 'Формулы',
        icon: icon(MdFunctions),
        color: '#581c87',
        canAddMultiple: true,
        description: 'Формулы с названиями, переменными и величинами',
        fields: [
            { key: 'formulaName', label: 'Название формулы', inputType: 'text', placeholder: 'Формула статистической значимости' },
            { key: 'formulaLatex', label: 'LaTeX', inputType: 'textarea', placeholder: 'p = 1 - F(x; \\nu)' },
            { key: 'formulaVariables', label: 'Переменные', inputType: 'key-value-list', placeholder: 'Каждая строка: переменная: значение/описание' },
        ],
    },
    {
        designation: 'causal_graph',
        name: 'Каузальные графы (DAG)',
        icon: icon(MdAccountTree),
        color: '#6d28d9',
        canAddMultiple: true,
        description: 'Directed Acyclic Graph каузальных зависимостей',
        fields: [
            { key: 'dagDescription', label: 'Описание', inputType: 'textarea', placeholder: 'Описание графа причинно-следственных связей' },
            { key: 'dagData', label: 'Данные графа (JSON)', inputType: 'textarea', placeholder: '{"nodes": [...], "edges": [...]}' },
        ],
    },
    {
        designation: 'identifiability_criteria',
        name: 'Критерии идентифицируемости Дж.Перла',
        icon: icon(MdSearch),
        color: '#7e22ce',
        canAddMultiple: false,
        description: 'Критерии идентифицируемости по Дж.Перлу',
        fields: [
            { key: 'criteria', label: 'Критерии', inputType: 'textarea', placeholder: 'Описание критериев идентифицируемости' },
        ],
    },
    {
        designation: 'result',
        name: 'Результаты',
        icon: icon(MdAssessment),
        color: '#0f766e',
        canAddMultiple: false,
        description: 'Результаты в стандартной форме (таблицы данных)',
        fields: [
            { key: 'results', label: 'Результаты', inputType: 'textarea', placeholder: 'Таблицы данных, описания результатов' },
            { key: 'resultsSummary', label: 'Краткое описание', inputType: 'text', placeholder: 'Краткое описание основных результатов' },
        ],
    },
    {
        designation: 'statistical_processing',
        name: 'Статистическая обработка',
        icon: icon(MdCalculate),
        color: '#155e75',
        canAddMultiple: false,
        description: 'Стандартная статистическая обработка и сопоставление с ожиданиями',
        fields: [
            { key: 'statProcessing', label: 'Статистическая обработка', inputType: 'textarea', placeholder: 'Какие тесты применялись' },
            { key: 'expectationsComparison', label: 'Сопоставление с ожиданиями', inputType: 'textarea', placeholder: 'Что подтверждено, что опровергнуто' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'claim',
        name: 'Утверждение',
        icon: icon(MdFactCheck),
        color: '#059669',
        canAddMultiple: true,
        description: 'На каждое утверждение может быть противоположное с "не"',
        fields: [
            { key: 'claimSubject', label: 'Субъект', inputType: 'text', placeholder: 'Субъект утверждения', required: true },
            {
                key: 'claimPredicate', label: 'Предикат', inputType: 'select',
                options: [
                    'is_a', 'causes', 'inhibits', 'activates',
                    'correlates with', 'affects', 'associated with', 'defines',
                    'contains', 'participates in', 'modulates', 'neutralizes',
                ],
                required: true,
            },
            { key: 'claimObject', label: 'Объект', inputType: 'text', placeholder: 'Объект утверждения', required: true },
            { key: 'confidenceNotes', label: 'Степень уверенности', inputType: 'textarea', placeholder: 'Список: почему нужно доверять утверждению (поддерживается N экспериментами и т.д.)' },
            { key: 'isNegated', label: 'Отрицание (не)', inputType: 'checkbox' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'limitations',
        name: 'Ограничения исследования',
        icon: icon(MdWarning),
        color: '#d97706',
        canAddMultiple: false,
        description: 'Ограничения данного исследования',
        fields: [
            { key: 'limitations', label: 'Ограничения', inputType: 'textarea', placeholder: 'Перечислите ограничения' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'side_findings',
        name: 'Побочные выводы/гипотезы',
        icon: icon(MdLightbulb),
        color: '#ea580c',
        canAddMultiple: false,
        description: 'Какие побочные выводы или гипотезы показало исследование',
        fields: [
            { key: 'sideFindings', label: 'Побочные выводы', inputType: 'textarea', placeholder: 'Неожиданные находки и новые гипотезы' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'side_effects',
        name: 'Сопутствующие эффекты',
        icon: icon(MdFlashOn),
        color: '#ca8a04',
        canAddMultiple: false,
        description: 'Сопутствующие эффекты вмешательства',
        fields: [
            { key: 'sideEffects', label: 'Побочные эффекты', inputType: 'textarea', placeholder: 'Описание сопутствующих эффектов' },
        ],
    },
    {
        designation: 'post_claims',
        name: 'Утверждения после исследования',
        icon: icon(MdCheckCircleOutline),
        color: '#16a34a',
        canAddMultiple: false,
        description: 'Что теперь можем утверждать в виде утверждений',
        fields: [
            { key: 'postClaims', label: 'Утверждения', inputType: 'textarea', placeholder: 'Каждое утверждение с новой строки' },
            { key: 'comparisonWithExpectations', label: 'Сравнение с ожиданиями', inputType: 'textarea', placeholder: 'Что подтверждено, что опровергнуто' },
        ],
    },
    {
        designation: 'open_questions',
        name: 'Оставшиеся вопросы',
        icon: icon(MdHelpOutline),
        color: '#7c3aed',
        canAddMultiple: false,
        description: 'Открытые вопросы после исследования',
        fields: [
            { key: 'openQuestions', label: 'Открытые вопросы', inputType: 'textarea', placeholder: 'Какие вопросы остаются открытыми' },
        ],
    },
    {
        designation: 'novelty',
        name: 'Новизна',
        icon: icon(MdAutoAwesome),
        color: '#6366f1',
        canAddMultiple: false,
        description: 'Научная новизна работы',
        fields: [
            { key: 'novelty', label: 'Новизна', inputType: 'textarea', placeholder: 'В чём научная новизна?' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'versions',
        name: 'Версии',
        icon: icon(MdUpdate),
        color: '#525252',
        canAddMultiple: false,
        description: 'Версии: ПО, датасета, протокола, модели и т.д.',
        fields: [
            { key: 'versions', label: 'Версии', inputType: 'key-value-list', placeholder: 'Каждая строка: компонент: версия' },
        ],
    },
    {
        designation: 'future_research_suggestions',
        name: 'Предложения для будущих исследований',
        icon: icon(MdLightbulbOutline),
        color: '#0284c7',
        canAddMultiple: false,
        description: 'Какие эксперименты наиболее полезно провести',
        fields: [
            { key: 'futureResearch', label: 'Предложения', inputType: 'textarea', placeholder: 'Какие эксперименты стоит провести дальше' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'reference',
        name: 'Связи с предыдущими исследованиями',
        icon: icon(MdFormatQuote),
        color: '#64748b',
        canAddMultiple: false,
        description: 'Библиографические ссылки и связи',
        fields: [
            { key: 'references', label: 'Ссылки', inputType: 'textarea', placeholder: 'Каждая ссылка с новой строки' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'link_with_aging',
        name: 'Связь со старением',
        icon: icon(MdHourglassBottom),
        color: '#a16207',
        canAddMultiple: false,
        description: 'Связь с процессами старения или продления жизни',
        fields: [
            { key: 'agingConnection', label: 'Связь', inputType: 'textarea', placeholder: 'Как исследование связано со старением/продлением жизни' },
        ],
    },
    {
        designation: 'image',
        name: 'Изображение',
        icon: icon(MdImage),
        color: '#0e7490',
        canAddMultiple: false,
        description: 'Изображение с возможностью загрузки и замены файла',
        fields: [
            { key: 'imageKey', label: 'Изображение', inputType: 'image-upload', placeholder: 'Загрузите изображение', helpText: 'Загрузка/замена файла изображения (PNG, JPG, SVG и др.)' },
            { key: 'caption', label: 'Подпись', inputType: 'text', placeholder: 'Fig. 1N — подпись к рисунку' },
            { key: 'imageRefs', label: 'Дополнительные ссылки', inputType: 'textarea', placeholder: 'Каждая ссылка/path с новой строки' },
        ],
    },
    {
        designation: 'code',
        name: 'Код',
        icon: icon(MdCode),
        color: '#1f2937',
        canAddMultiple: true,
        description: 'Код, использованный в анализе',
        fields: [
            { key: 'codeLanguage', label: 'Язык', inputType: 'select', options: ['Python', 'R', 'Julia', 'SQL', 'Другой'] },
            { key: 'code', label: 'Код', inputType: 'textarea', placeholder: '# Ваш код здесь' },
        ],
    },
    {
        designation: 'funding',
        name: 'Источники финансирования',
        icon: icon(MdAttachMoney),
        color: '#166534',
        canAddMultiple: false,
        description: 'Гранты и спонсоры',
        fields: [
            { key: 'funding', label: 'Финансирование', inputType: 'textarea', placeholder: 'Источники финансирования' },
        ],
    },
    {
        designation: 'interest_conflict',
        name: 'Конфликт интересов',
        icon: icon(MdBalance),
        color: '#991b1b',
        canAddMultiple: false,
        description: 'Заявление о конфликте интересов',
        fields: [
            { key: 'conflictOfInterest', label: 'Конфликт интересов', inputType: 'textarea', placeholder: 'Заявление о конфликте интересов' },
        ],
    },
    {
        designation: 'scientific_knowledge_value',
        name: 'Информационная ценность',
        icon: icon(MdTrendingUp),
        color: '#0369a1',
        canAddMultiple: false,
        description: 'Какую неопределённость уменьшило исследование',
        fields: [
            { key: 'uncertaintyReduced', label: 'Какую неопределённость уменьшило', inputType: 'textarea', placeholder: '' },
            { key: 'hypothesesExcluded', label: 'Какие гипотезы исключены', inputType: 'textarea', placeholder: '' },
            { key: 'hypothesesProbabilized', label: 'Какие гипотезы стали вероятнее', inputType: 'textarea', placeholder: '' },
            { key: 'newHypotheses', label: 'Какие новые гипотезы появились', inputType: 'textarea', placeholder: '' },
            { key: 'nextExperiment', label: 'Какой следующий эксперимент даст наибольший прирост', inputType: 'textarea', placeholder: '' },
        ],
    },
    {
        designation: 'action',
        name: 'Действие',
        icon: icon(MdPlayArrow),
        color: '#c2410c',
        canAddMultiple: true,
        layout: 'row',
        description: 'Триплет действия: что делаем → к чему → с каким объектом',
        fields: [
            { key: 'subject', label: 'Действие', inputType: 'uuid-ref', placeholder: 'идентификация' },
            { key: 'predicate', label: 'Связь', inputType: 'text', placeholder: 'чего' },
            { key: 'object', label: 'Объект', inputType: 'uuid-ref', placeholder: 'механизм резистентности...' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'animal_group',
        name: 'Группа животных',
        icon: icon(MdGroup),
        color: '#4f46e5',
        canAddMultiple: true,
        description: 'Одна группа животных (повторяемый блок: контрольная или экспериментальная)',
        fields: [
            { key: 'groupName', label: 'Название группы', inputType: 'text', placeholder: 'Aged A. russatus' },
            { key: 'speciesRef', label: 'Животная модель (UUID)', inputType: 'uuid-ref', placeholder: 'ссылка на animal_model', uuidRefBlockTypes: ['animal_model'] },
            { key: 'n', label: 'Размер выборки', inputType: 'text', placeholder: 'n=10' },
            { key: 'conditions', label: 'Условия', inputType: 'textarea', placeholder: 'Условия содержания во время эксперимента' },
            { key: 'purpose', label: 'Назначение', inputType: 'text', placeholder: 'baseline, возрастной контроль, интервенция...' },
        ],
    },
    {
        designation: 'experiment_step',
        name: 'Шаг эксперимента',
        icon: icon(MdFormatListNumbered),
        color: '#7c3aed',
        canAddMultiple: true,
        description: 'Один шаг последовательности действий эксперимента',
        fields: [
            { key: 'stepName', label: 'Название шага', inputType: 'text', placeholder: 'Open field test' },
            { key: 'details', label: 'Детали', inputType: 'textarea', placeholder: 'Параметры, условия, n на группу' },
            { key: 'duration', label: 'Длительность', inputType: 'text', placeholder: '10 мин, 5 недель...' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'finding',
        name: 'Результат (находка)',
        icon: icon(MdTrendingUp),
        color: '#db2777',
        canAddMultiple: true,
        description: 'Одна находка исследования: параметр → направление изменения → группа',
        fields: [
            { key: 'parameter', label: 'Параметр/фенотип', inputType: 'text', placeholder: 'p16+ клетки в VAT', required: true },
            { key: 'subjectRef', label: 'Группа/условие (UUID)', inputType: 'uuid-ref', placeholder: 'ссылка на animal_group', uuidRefBlockTypes: ['animal_group'], helpText: 'Группа животных (animal_group), в которой наблюдается результат' },
            { key: 'comparisonRef', label: 'Сравнение (UUID)', inputType: 'uuid-ref', placeholder: 'ссылка на animal_group (опционально)', uuidRefBlockTypes: ['animal_group'], helpText: 'Группа сравнения (animal_group), относительно которой оценивается изменение' },
            { key: 'direction', label: 'Направление', inputType: 'select', options: ['повышено', 'понижено', 'без изменений', 'тренд'] },
            { key: 'significance', label: 'Значимость', inputType: 'select', options: ['significant', 'non-significant', 'trend'] },
            { key: 'pValue', label: 'p-value (UUID)', inputType: 'uuid-ref', placeholder: 'ссылка на probability_value', uuidRefBlockTypes: ['probability_value'], helpText: 'Ссылка на блок p-value (probability_value)' },
            { key: 'figureRef', label: 'Рисунок', inputType: 'text', placeholder: 'Fig. 1N, fig. S4G' },
            { key: 'detail', label: 'Детали', inputType: 'textarea', placeholder: 'Детали результата: величины, % изменения и т.п.' },
            TRIPLET_SEQUENCE_FIELD,
        ],
    },
    {
        designation: 'relation',
        name: 'Причинно-следственная связь',
        icon: icon(MdLink),
        color: '#a21caf',
        canAddMultiple: true,
        description: 'Зависимость действий (T58): источник → связь → цель',
        fields: [
            { key: 'source', label: 'Источник', inputType: 'text', placeholder: 'mTOR hyperfunction' },
            { key: 'target', label: 'Цель', inputType: 'text', placeholder: 'cellular senescence' },
            {
                key: 'relationType', label: 'Тип связи', inputType: 'select',
                options: ['causes', 'enables', 'requires', 'precedes', 'inhibits', 'prevents', 'leads_to', 'enhances', 'suppresses'],
            },
            { key: 'confidence', label: 'Уверенность', inputType: 'select', options: ['high', 'medium', 'low'] },
            { key: 'evidence', label: 'Доказательства', inputType: 'textarea', placeholder: 'Краткое описание подтверждающего факта (3-8 слов)' },
        ],
    },
    {
        designation: 'temporal_relation',
        name: 'Временная последовательность',
        icon: icon(MdTimeline),
        color: '#155e75',
        canAddMultiple: true,
        description: 'Порядок событий (T59): раньше → связь → позже',
        fields: [
            { key: 'earlier', label: 'Раньше', inputType: 'text', placeholder: 'Событие, происходящее раньше' },
            { key: 'later', label: 'Позже', inputType: 'text', placeholder: 'Событие, происходящее позже' },
            { key: 'relationType', label: 'Тип связи', inputType: 'select', options: ['precedes', 'follows', 'during'] },
        ],
    },
];

export const BLOCK_TYPE_MAP: Map<string, BlockTypeDef> = new Map(
    BLOCK_TYPES.map((t) => [t.designation, t]),
);

export function getBlockTypeDef(designation: string): BlockTypeDef | undefined {
    return BLOCK_TYPE_MAP.get(designation);
}