apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: knowledge-map
spec:
  template:
    spec:
      containers:
        - name: billing
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "512Mi"
              cpu: "0.5"
