apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-map-core
  namespace: knowledge-map
spec:
  template:
    spec:
      containers:
        - name: knowledge-map-core
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.5"
