apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp
  namespace: knowledge-map
spec:
  template:
    spec:
      containers:
        - name: nlp
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
