# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import xml_to_md_pb2 as xml__to__md__pb2


class XmlToMarkdownServiceStub(object):
    """Сервис для конвертации PubMed/PMC XML в Markdown
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertPmcXml = channel.unary_unary(
                '/xml_to_md.XmlToMarkdownService/ConvertPmcXml',
                request_serializer=xml__to__md__pb2.ConvertPmcXmlRequest.SerializeToString,
                response_deserializer=xml__to__md__pb2.ConvertXmlResponse.FromString,
                )
        self.ParsePubmedMetadata = channel.unary_unary(
                '/xml_to_md.XmlToMarkdownService/ParsePubmedMetadata',
                request_serializer=xml__to__md__pb2.ParsePubmedMetadataRequest.SerializeToString,
                response_deserializer=xml__to__md__pb2.ParseMetadataResponse.FromString,
                )


class XmlToMarkdownServiceServicer(object):
    """Сервис для конвертации PubMed/PMC XML в Markdown
    """

    def ConvertPmcXml(self, request, context):
        """Конвертация PMC NLM DTD XML в Markdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParsePubmedMetadata(self, request, context):
        """Парсинг PubMed efetch XML → список метаданных статей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XmlToMarkdownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertPmcXml': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertPmcXml,
                    request_deserializer=xml__to__md__pb2.ConvertPmcXmlRequest.FromString,
                    response_serializer=xml__to__md__pb2.ConvertXmlResponse.SerializeToString,
            ),
            'ParsePubmedMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ParsePubmedMetadata,
                    request_deserializer=xml__to__md__pb2.ParsePubmedMetadataRequest.FromString,
                    response_serializer=xml__to__md__pb2.ParseMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xml_to_md.XmlToMarkdownService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XmlToMarkdownService(object):
    """Сервис для конвертации PubMed/PMC XML в Markdown
    """

    @staticmethod
    def ConvertPmcXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xml_to_md.XmlToMarkdownService/ConvertPmcXml',
            xml__to__md__pb2.ConvertPmcXmlRequest.SerializeToString,
            xml__to__md__pb2.ConvertXmlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParsePubmedMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xml_to_md.XmlToMarkdownService/ParsePubmedMetadata',
            xml__to__md__pb2.ParsePubmedMetadataRequest.SerializeToString,
            xml__to__md__pb2.ParseMetadataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
