# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xml_to_md.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxml_to_md.proto\x12\txml_to_md\"\xc9\x01\n\x14\x43onvertPmcXmlRequest\x12\x11\n\txml_bytes\x18\x01 \x01(\x0c\x12\x42\n\nimage_urls\x18\x02 \x03(\x0b\x32..xml_to_md.ConvertPmcXmlRequest.ImageUrlsEntry\x12(\n\x08provider\x18\x03 \x01(\x0e\x32\x16.xml_to_md.XmlProvider\x1a\x30\n\x0eImageUrlsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\x12\x43onvertXmlResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10markdown_content\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"/\n\x1aParsePubmedMetadataRequest\x12\x11\n\txml_bytes\x18\x01 \x01(\x0c\"\x81\x01\n\x0f\x41rticleMetadata\x12\x0c\n\x04pmid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\x0f\n\x07journal\x18\x04 \x01(\t\x12\x10\n\x08pub_date\x18\x05 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x06 \x01(\t\x12\x0b\n\x03\x64oi\x18\x07 \x01(\t\"g\n\x15ParseMetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12,\n\x08\x61rticles\x18\x02 \x03(\x0b\x32\x1a.xml_to_md.ArticleMetadata\x12\x0f\n\x07message\x18\x03 \x01(\t*<\n\x0bXmlProvider\x12\x18\n\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x07\n\x03PMC\x10\x01\x12\n\n\x06PUBMED\x10\x02\x32\xc7\x01\n\x14XmlToMarkdownService\x12O\n\rConvertPmcXml\x12\x1f.xml_to_md.ConvertPmcXmlRequest\x1a\x1d.xml_to_md.ConvertXmlResponse\x12^\n\x13ParsePubmedMetadata\x12%.xml_to_md.ParsePubmedMetadataRequest\x1a .xml_to_md.ParseMetadataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xml_to_md_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERTPMCXMLREQUEST_IMAGEURLSENTRY']._options = None
  _globals['_CONVERTPMCXMLREQUEST_IMAGEURLSENTRY']._serialized_options = b'8\001'
  _globals['_XMLPROVIDER']._serialized_start=602
  _globals['_XMLPROVIDER']._serialized_end=662
  _globals['_CONVERTPMCXMLREQUEST']._serialized_start=31
  _globals['_CONVERTPMCXMLREQUEST']._serialized_end=232
  _globals['_CONVERTPMCXMLREQUEST_IMAGEURLSENTRY']._serialized_start=184
  _globals['_CONVERTPMCXMLREQUEST_IMAGEURLSENTRY']._serialized_end=232
  _globals['_CONVERTXMLRESPONSE']._serialized_start=234
  _globals['_CONVERTXMLRESPONSE']._serialized_end=314
  _globals['_PARSEPUBMEDMETADATAREQUEST']._serialized_start=316
  _globals['_PARSEPUBMEDMETADATAREQUEST']._serialized_end=363
  _globals['_ARTICLEMETADATA']._serialized_start=366
  _globals['_ARTICLEMETADATA']._serialized_end=495
  _globals['_PARSEMETADATARESPONSE']._serialized_start=497
  _globals['_PARSEMETADATARESPONSE']._serialized_end=600
  _globals['_XMLTOMARKDOWNSERVICE']._serialized_start=665
  _globals['_XMLTOMARKDOWNSERVICE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
