apiVersion: v1
kind: Service
metadata:
  name: knowledge-map-core
  namespace: knowledge-map
spec:
  selector:
    app: knowledge-map-core
  ports:
    - name: grpc
      port: 50056
      targetPort: grpc
  type: ClusterIP
