apiVersion: v1
kind: Service
metadata:
  name: layout
  namespace: knowledge-map
spec:
  selector:
    app: layout
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: metrics
      port: 9090
      targetPort: metrics
  type: ClusterIP
