# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import knowledge_language_pb2 as knowledge__language__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in knowledge_language_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeLanguageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessText = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/ProcessText',
                request_serializer=knowledge__language__pb2.ProcessTextRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.KnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/HealthCheck',
                request_serializer=knowledge__language__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.CheckUniqueness = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/CheckUniqueness',
                request_serializer=knowledge__language__pb2.CheckUniquenessRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.UniquenessResponse.FromString,
                _registered_method=True)
        self.CheckSubgraphUniqueness = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/CheckSubgraphUniqueness',
                request_serializer=knowledge__language__pb2.CheckSubgraphUniquenessRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.SubgraphUniquenessResponse.FromString,
                _registered_method=True)
        self.CheckPatternMatch = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/CheckPatternMatch',
                request_serializer=knowledge__language__pb2.CheckPatternMatchRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.PatternMatchResponse.FromString,
                _registered_method=True)
        self.AddStatementWithUniqueness = channel.unary_unary(
                '/knowledge_language.KnowledgeLanguageService/AddStatementWithUniqueness',
                request_serializer=knowledge__language__pb2.AddStatementRequest.SerializeToString,
                response_deserializer=knowledge__language__pb2.AddStatementResponse.FromString,
                _registered_method=True)


class KnowledgeLanguageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUniqueness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSubgraphUniqueness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPatternMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStatementWithUniqueness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeLanguageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessText': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessText,
                    request_deserializer=knowledge__language__pb2.ProcessTextRequest.FromString,
                    response_serializer=knowledge__language__pb2.KnowledgeGraphResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=knowledge__language__pb2.HealthCheckRequest.FromString,
                    response_serializer=knowledge__language__pb2.HealthCheckResponse.SerializeToString,
            ),
            'CheckUniqueness': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUniqueness,
                    request_deserializer=knowledge__language__pb2.CheckUniquenessRequest.FromString,
                    response_serializer=knowledge__language__pb2.UniquenessResponse.SerializeToString,
            ),
            'CheckSubgraphUniqueness': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSubgraphUniqueness,
                    request_deserializer=knowledge__language__pb2.CheckSubgraphUniquenessRequest.FromString,
                    response_serializer=knowledge__language__pb2.SubgraphUniquenessResponse.SerializeToString,
            ),
            'CheckPatternMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPatternMatch,
                    request_deserializer=knowledge__language__pb2.CheckPatternMatchRequest.FromString,
                    response_serializer=knowledge__language__pb2.PatternMatchResponse.SerializeToString,
            ),
            'AddStatementWithUniqueness': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStatementWithUniqueness,
                    request_deserializer=knowledge__language__pb2.AddStatementRequest.FromString,
                    response_serializer=knowledge__language__pb2.AddStatementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'knowledge_language.KnowledgeLanguageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('knowledge_language.KnowledgeLanguageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeLanguageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/ProcessText',
            knowledge__language__pb2.ProcessTextRequest.SerializeToString,
            knowledge__language__pb2.KnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/HealthCheck',
            knowledge__language__pb2.HealthCheckRequest.SerializeToString,
            knowledge__language__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUniqueness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/CheckUniqueness',
            knowledge__language__pb2.CheckUniquenessRequest.SerializeToString,
            knowledge__language__pb2.UniquenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSubgraphUniqueness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/CheckSubgraphUniqueness',
            knowledge__language__pb2.CheckSubgraphUniquenessRequest.SerializeToString,
            knowledge__language__pb2.SubgraphUniquenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPatternMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/CheckPatternMatch',
            knowledge__language__pb2.CheckPatternMatchRequest.SerializeToString,
            knowledge__language__pb2.PatternMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStatementWithUniqueness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge_language.KnowledgeLanguageService/AddStatementWithUniqueness',
            knowledge__language__pb2.AddStatementRequest.SerializeToString,
            knowledge__language__pb2.AddStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
