#!/usr/bin/env bash
# Генерирует deploy/k8s/overlays/prod/secrets.env из секретов GitHub Actions.
# Скрипт выполняет gitignore-style защиту: secrets.env не коммитится.
set -euo pipefail

OVERLAY_DIR="deploy/k8s/overlays/prod"
OUT="$OVERLAY_DIR/secrets.env"

: "${NEO4J_PASSWORD:=CHANGE_ME}"
: "${SECRET_KEY:=CHANGE_ME}"
: "${INTERNAL_TOKEN:=CHANGE_ME}"
: "${S3_ACCESS_KEY:=CHANGE_ME}"
: "${S3_SECRET_KEY:=CHANGE_ME}"
: "${YOOKASSA_SHOP_ID:=CHANGE_ME}"
: "${YOOKASSA_SECRET_KEY:=CHANGE_ME}"
: "${CLOUDRU_API_KEY:=CHANGE_ME}"
: "${OPENALEX_API_KEY:=CHANGE_ME}"
: "${OPENCITATIONS_ACCESS_TOKEN:=CHANGE_ME}"
: "${NCBI_API_KEY:=CHANGE_ME}"
: "${HUGGING_FACE_TOKEN:=CHANGE_ME}"

cat > "$OUT" <<EOF
NEO4J_PASSWORD=${NEO4J_PASSWORD}
SECRET_KEY=${SECRET_KEY}
INTERNAL_TOKEN=${INTERNAL_TOKEN}
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
CLOUDRU_API_KEY=${CLOUDRU_API_KEY}
OPENALEX_API_KEY=${OPENALEX_API_KEY}
OPENCITATIONS_ACCESS_TOKEN=${OPENCITATIONS_ACCESS_TOKEN}
NCBI_API_KEY=${NCBI_API_KEY}
HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
EOF

echo "secrets.env assembled at $OUT"