"""Порты независимого преобразования текста и хранения карт статьи."""
from typing import Protocol


class ArticleMapsRepository(Protocol):
    def authorize(self, article_id: str, user_uid: str) -> None: ...
    def ensure_schema(self) -> None: ...
    def list_maps(self, article_id: str, user_uid: str) -> list[dict]: ...
    def get(self, article_id: str, pipeline_id: str, user_uid: str) -> dict | None: ...
    def acquire(self, article_id: str, pipeline_id: str, user_uid: str, token: str) -> None: ...
    def renew(self, article_id: str, pipeline_id: str, user_uid: str, token: str) -> None: ...
    def release(self, article_id: str, pipeline_id: str, user_uid: str, token: str) -> None: ...
    def save(self, result: dict, user_uid: str, token: str) -> None: ...
    def save_translation(self, article_id: str, pipeline_id: str, user_uid: str,
                         run_id: str, translations: dict, token: str) -> None: ...


class ArticleMapModel(Protocol):
    last_call: dict
    async def __call__(self, system: str, user: str) -> str: ...


class ArticleMapSource(Protocol):
    async def read_text(self, article_id: str, user_uid: str) -> str: ...
