"""Persistence port used by versioned article extraction."""
from typing import Protocol

class ArticlePipelineRepository(Protocol):
    def save(self, result: dict, user_uid: str) -> None: ...
    def load(self, doc_id: str, version_id: str, user_uid: str) -> dict: ...
    def versions(self, doc_id: str, user_uid: str) -> list[dict]: ...
    def save_map_snapshot(self, doc_id: str, user_uid: str, graph: dict,
                          blocks_fingerprint: str) -> None: ...
    def load_map_snapshot(self, doc_id: str, user_uid: str) -> dict | None: ...
    def apply(self, doc_id: str, version_id: str, user_uid: str, source_hash: str) -> None: ...
