"""Порты изолированного эксперимента с прямыми картами знаний."""
from typing import Protocol


class ReferenceSourceProvider(Protocol):
    async def registry(self) -> dict: ...
    async def materialize(self, reference: dict) -> dict: ...
    async def target(self) -> dict: ...


class PilotMapBuilder(Protocol):
    calls: list[dict]
    async def build(self, source: dict) -> dict: ...


class ExperimentStore(Protocol):
    def read(self, relative: str) -> dict | None: ...
    def write(self, relative: str, value, *, immutable: bool = True) -> None: ...
    def write_bytes(self, relative: str, data: bytes, *, immutable: bool = True) -> None: ...
