# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_model_pb2 as ai__model__pb2


class AIModelServiceStub(object):
    """AI Model Service for text generation using Hugging Face models
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/ai_model.AIModelService/GenerateText',
                request_serializer=ai__model__pb2.GenerateTextRequest.SerializeToString,
                response_deserializer=ai__model__pb2.GenerateTextResponse.FromString,
                )
        self.GetModels = channel.unary_unary(
                '/ai_model.AIModelService/GetModels',
                request_serializer=ai__model__pb2.GetModelsRequest.SerializeToString,
                response_deserializer=ai__model__pb2.GetModelsResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/ai_model.AIModelService/HealthCheck',
                request_serializer=ai__model__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__model__pb2.HealthCheckResponse.FromString,
                )


class AIModelServiceServicer(object):
    """AI Model Service for text generation using Hugging Face models
    """

    def GenerateText(self, request, context):
        """Generate text based on a prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModels(self, request, context):
        """Get list of available models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=ai__model__pb2.GenerateTextRequest.FromString,
                    response_serializer=ai__model__pb2.GenerateTextResponse.SerializeToString,
            ),
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=ai__model__pb2.GetModelsRequest.FromString,
                    response_serializer=ai__model__pb2.GetModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__model__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__model__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_model.AIModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIModelService(object):
    """AI Model Service for text generation using Hugging Face models
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_model.AIModelService/GenerateText',
            ai__model__pb2.GenerateTextRequest.SerializeToString,
            ai__model__pb2.GenerateTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_model.AIModelService/GetModels',
            ai__model__pb2.GetModelsRequest.SerializeToString,
            ai__model__pb2.GetModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_model.AIModelService/HealthCheck',
            ai__model__pb2.HealthCheckRequest.SerializeToString,
            ai__model__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
