# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pdf_to_md_pb2 as pdf__to__md__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pdf_to_md_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDFToMarkdownServiceStub(object):
    """Сервис для конвертации PDF в Markdown
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertPDF = channel.unary_unary(
                '/pdf_to_md.PDFToMarkdownService/ConvertPDF',
                request_serializer=pdf__to__md__pb2.ConvertPDFRequest.SerializeToString,
                response_deserializer=pdf__to__md__pb2.ConvertPDFResponse.FromString,
                _registered_method=True)
        self.GetModels = channel.unary_unary(
                '/pdf_to_md.PDFToMarkdownService/GetModels',
                request_serializer=pdf__to__md__pb2.GetModelsRequest.SerializeToString,
                response_deserializer=pdf__to__md__pb2.GetModelsResponse.FromString,
                _registered_method=True)
        self.SetDefaultModel = channel.unary_unary(
                '/pdf_to_md.PDFToMarkdownService/SetDefaultModel',
                request_serializer=pdf__to__md__pb2.SetDefaultModelRequest.SerializeToString,
                response_deserializer=pdf__to__md__pb2.SetDefaultModelResponse.FromString,
                _registered_method=True)
        self.EnableModel = channel.unary_unary(
                '/pdf_to_md.PDFToMarkdownService/EnableModel',
                request_serializer=pdf__to__md__pb2.EnableModelRequest.SerializeToString,
                response_deserializer=pdf__to__md__pb2.EnableModelResponse.FromString,
                _registered_method=True)
        self.ConvertPDFWithProgress = channel.unary_stream(
                '/pdf_to_md.PDFToMarkdownService/ConvertPDFWithProgress',
                request_serializer=pdf__to__md__pb2.ConvertPDFRequest.SerializeToString,
                response_deserializer=pdf__to__md__pb2.ProgressUpdate.FromString,
                _registered_method=True)


class PDFToMarkdownServiceServicer(object):
    """Сервис для конвертации PDF в Markdown
    """

    def ConvertPDF(self, request, context):
        """Конвертация PDF в Markdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModels(self, request, context):
        """Получение списка доступных моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultModel(self, request, context):
        """Установка модели по умолчанию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableModel(self, request, context):
        """Включение/отключение модели
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertPDFWithProgress(self, request, context):
        """Конвертация с отслеживанием прогресса (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDFToMarkdownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertPDF,
                    request_deserializer=pdf__to__md__pb2.ConvertPDFRequest.FromString,
                    response_serializer=pdf__to__md__pb2.ConvertPDFResponse.SerializeToString,
            ),
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=pdf__to__md__pb2.GetModelsRequest.FromString,
                    response_serializer=pdf__to__md__pb2.GetModelsResponse.SerializeToString,
            ),
            'SetDefaultModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultModel,
                    request_deserializer=pdf__to__md__pb2.SetDefaultModelRequest.FromString,
                    response_serializer=pdf__to__md__pb2.SetDefaultModelResponse.SerializeToString,
            ),
            'EnableModel': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableModel,
                    request_deserializer=pdf__to__md__pb2.EnableModelRequest.FromString,
                    response_serializer=pdf__to__md__pb2.EnableModelResponse.SerializeToString,
            ),
            'ConvertPDFWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.ConvertPDFWithProgress,
                    request_deserializer=pdf__to__md__pb2.ConvertPDFRequest.FromString,
                    response_serializer=pdf__to__md__pb2.ProgressUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdf_to_md.PDFToMarkdownService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdf_to_md.PDFToMarkdownService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDFToMarkdownService(object):
    """Сервис для конвертации PDF в Markdown
    """

    @staticmethod
    def ConvertPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdf_to_md.PDFToMarkdownService/ConvertPDF',
            pdf__to__md__pb2.ConvertPDFRequest.SerializeToString,
            pdf__to__md__pb2.ConvertPDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdf_to_md.PDFToMarkdownService/GetModels',
            pdf__to__md__pb2.GetModelsRequest.SerializeToString,
            pdf__to__md__pb2.GetModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdf_to_md.PDFToMarkdownService/SetDefaultModel',
            pdf__to__md__pb2.SetDefaultModelRequest.SerializeToString,
            pdf__to__md__pb2.SetDefaultModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdf_to_md.PDFToMarkdownService/EnableModel',
            pdf__to__md__pb2.EnableModelRequest.SerializeToString,
            pdf__to__md__pb2.EnableModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertPDFWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pdf_to_md.PDFToMarkdownService/ConvertPDFWithProgress',
            pdf__to__md__pb2.ConvertPDFRequest.SerializeToString,
            pdf__to__md__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
