"""
Layer: Application
Package: application.ports.repositories
Responsibility: Абстракции (Protocol) репозиториев для доменных моделей.
"""
from datetime import datetime
from typing import List, Optional, Protocol

from domain.models import (
    CreditAccount,
    CreditTransaction,
    Payment,
    PaymentEvent,
    Plan,
    Refund,
    Subscription,
)


class PlanRepositoryProtocol(Protocol):
    def list_active(self) -> List[Plan]: ...
    def get_by_code(self, code: str) -> Optional[Plan]: ...


class SubscriptionRepositoryProtocol(Protocol):
    def get_active_by_user(self, user_id: str) -> Optional[Subscription]: ...
    def get_by_uid(self, uid: str) -> Optional[Subscription]: ...
    def save(self, subscription: Subscription) -> Subscription: ...
    def list_by_user(self, user_id: str) -> List[Subscription]: ...


class PaymentRepositoryProtocol(Protocol):
    def create(self, payment: Payment) -> Payment: ...
    def save(self, payment: Payment) -> Payment: ...
    def get_by_uid(self, uid: str) -> Optional[Payment]: ...
    def get_by_provider_id(self, provider_payment_id: str) -> Optional[Payment]: ...
    def list_by_user(self, user_id: str, limit: int = 50) -> List[Payment]: ...
    def list_pending_since(self, since: datetime) -> List[Payment]: ...


class PaymentEventRepositoryProtocol(Protocol):
    def get_by_external_event_id(self, external_event_id: str) -> Optional[PaymentEvent]: ...
    def save(self, event: PaymentEvent) -> PaymentEvent: ...


class RefundRepositoryProtocol(Protocol):
    def create(self, refund: Refund) -> Refund: ...
    def save(self, refund: Refund) -> Refund: ...
    def get_by_payment_uid(self, payment_uid: str) -> List[Refund]: ...
    def get_by_provider_refund_id(self, provider_refund_id: str) -> Optional[Refund]: ...


class CreditRepositoryProtocol(Protocol):
    def get_or_create_account(self, user_id: str) -> CreditAccount: ...
    def get_account(self, user_id: str) -> Optional[CreditAccount]: ...
    def get_balance(self, user_id: str) -> int: ...
    def apply_transaction(self, transaction: CreditTransaction) -> CreditAccount: ...
    def get_transaction_by_reference_id(self, reference_id: str) -> Optional[CreditTransaction]: ...
    def list_transactions(self, user_id: str, limit: int = 50) -> List[CreditTransaction]: ...
