apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: 'trace_id=([0-9a-fA-F]{16,32})'
          name: TraceID
          url: '${__value.raw}'
          urlDisplayLabel: 'Открыть в Tempo'

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '1m'
        spanEndTimeShift: '-1m'
        filterByTraceID: false
        spanTags: ['service.name', 'http.route']