"""
Pure transformation functions between different NLP representations.

All functions in this module are pure (no side effects, deterministic).
"""

from .spacy_to_unified import (
    token_to_unified,
    dependency_to_unified,
    entity_to_unified,
    extract_noun_phrases,
    extract_verb_phrases,
    sentence_to_unified,
    document_to_unified,
)

from .token_ops import (
    extract_content_words,
    extract_function_words,
    filter_by_pos,
    filter_by_lemma,
    exclude_stop_tokens,
    group_by_lemma,
    group_by_pos,
    group_by_morph_feature,
    get_pos_distribution,
    get_lemma_frequency,
    get_morph_feature_distribution,
    get_confidence_stats,
    find_token_by_index,
    find_tokens_by_text,
    find_tokens_by_morph,
    to_text,
    get_lemmas,
    get_pos_tags,
    get_span_text,
)

from .dependency_ops import (
    build_dependency_tree,
    build_dependency_tree_from_sentence,
    find_root,
    get_head,
    get_dependents,
    extract_subtree,
    get_path_to_root,
    find_lowest_common_ancestor,
    find_dependencies_by_relation,
    find_subject,
    find_objects,
    find_prepositional_phrases,
    get_relation_distribution,
    get_average_dependency_length,
    count_arcs,
    count_crossing_arcs,
    filter_dependencies_by_confidence,
    reindex_dependencies,
)

from .entity_ops import (
    filter_entities_by_type,
    filter_scientific_entities,
    filter_entities_by_confidence,
    filter_overlapping_entities,
    group_entities_by_type,
    get_entity_type_distribution,
    get_entity_texts,
    get_unique_entities,
    find_entities_by_text,
    find_entities_by_type_and_token,
    find_entities_spanning_indices,
    get_canonical_names,
    get_entity_ids,
    filter_entities_by_domain,
    get_domain_distribution,
    extend_entity_span,
    merge_adjacent_entities,
)

__all__ = [
    # spacy_to_unified
    "token_to_unified",
    "dependency_to_unified",
    "entity_to_unified",
    "extract_noun_phrases",
    "extract_verb_phrases",
    "sentence_to_unified",
    "document_to_unified",

    # token_ops
    "extract_content_words",
    "extract_function_words",
    "filter_by_pos",
    "filter_by_lemma",
    "exclude_stop_tokens",
    "group_by_lemma",
    "group_by_pos",
    "group_by_morph_feature",
    "get_pos_distribution",
    "get_lemma_frequency",
    "get_morph_feature_distribution",
    "get_confidence_stats",
    "find_token_by_index",
    "find_tokens_by_text",
    "find_tokens_by_morph",
    "to_text",
    "get_lemmas",
    "get_pos_tags",
    "get_span_text",

    # dependency_ops
    "build_dependency_tree",
    "build_dependency_tree_from_sentence",
    "find_root",
    "get_head",
    "get_dependents",
    "extract_subtree",
    "get_path_to_root",
    "find_lowest_common_ancestor",
    "find_dependencies_by_relation",
    "find_subject",
    "find_objects",
    "find_prepositional_phrases",
    "get_relation_distribution",
    "get_average_dependency_length",
    "count_arcs",
    "count_crossing_arcs",
    "filter_dependencies_by_confidence",
    "reindex_dependencies",

    # entity_ops
    "filter_entities_by_type",
    "filter_scientific_entities",
    "filter_entities_by_confidence",
    "filter_overlapping_entities",
    "group_entities_by_type",
    "get_entity_type_distribution",
    "get_entity_texts",
    "get_unique_entities",
    "find_entities_by_text",
    "find_entities_by_type_and_token",
    "find_entities_spanning_indices",
    "get_canonical_names",
    "get_entity_ids",
    "filter_entities_by_domain",
    "get_domain_distribution",
    "extend_entity_span",
    "merge_adjacent_entities",
]
